### ISSUE TITLE
Legislation Tracking

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-roadmap#15]
## Idea / Feature

Add functionality to the web application that allows for tracking matters through council.

## Use Case / User Story

I want to follow one specific bill as it goes through the council process. And see any amendments to it.

## Solution

Add a "Legislation" page that connects to the backend database "Matter" and related items. Additionally be able to search for matters from plain text.

## Stakeholders

1 or 2 backend (Shak and Isaac have already self-assigned)
1 or 2 UX
1 or 2 frontend

## Major Components

* [ ] https://github.com/CouncilDataProject/cdp-backend/issues/81
* [ ] https://github.com/CouncilDataProject/cdp-frontend/issues/56
* [ ] https://github.com/CouncilDataProject/cdp-frontend/issues/89
* [ ] https://github.com/CouncilDataProject/cdp-frontend/issues/90
* [ ] https://github.com/CouncilDataProject/cdp-frontend/issues/88
